# Generated by Django 4.1.2 on 2022-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profil_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
